baseURL = "https://everythoughthelps.github.io/"
languageCode = 'en-us'
title = "Pan's blog"
[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
author = "Pan Meng"
description = "Thoughts on technology, coding, and life ✨"

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 1  # 决定菜单顺序，数字越小越靠前

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3
