name: Deploy Hugo Blog

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # 如果使用了 Hugo 主题作为子模块，需要启用 submodules

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.143.1'  # 替换为你的 Hugo 版本
          extended: true  # 如果使用 Hugo Extended 版本

      - name: Build blog
        run: hugo --minify  # 生成静态文件

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 token
          publish_dir: ./public  # Hugo 生成的静态文件目录
          publish_branch: gh-pages  # 部署到的分支
